version: '3.5'

services:
    front:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:80        
      container_name: gecko-front
    nginx:
      image: nginx:1.20.1
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
      - "8080:80"
      container_name: reserve-proxy